fileserver:
  publicPort: 9000
  privatePort: 9001
  publicBaseUrl: "http://localhost:9000"
  storageDirectory: "/tmp/fileserver"
  maxUploadBytes: 10485760

logger:
  levels:
    root: INFO  # Set root log level
